import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "john123@Gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Chirstopher",
      email: "chris@Gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "Nike slim shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality products",
    },
    {
      name: "Addidas slim shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 130,
      countInStock: 12,
      brand: "Addidas",
      rating: 3,
      numReviews: 8,
      description: "Great T shirt",
    },
    {
      name: "Puma slim shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 100,
      countInStock: 50,
      brand: "Puma",
      rating: 5,
      numReviews: 5,
      description: "Great products",
    },
    {
      name: "Nike Trousers",
      category: "pants",
      image: "/images/p4.jpg",
      price: 80,
      countInStock: 0,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality products",
    },
    {
      name: "Puma Trousers",
      category: "pants",
      image: "/images/p5.jpg",
      price: 150,
      countInStock: 15,
      brand: "Puma",
      rating: 5,
      numReviews: 6,
      description: "High quality products",
    },
    {
      name: "Ducati Trousers",
      category: "pants",
      image: "/images/p6.jpg",
      price: 200,
      countInStock: 11,
      brand: "Ducati",
      rating: 3,
      numReviews: 7,
      description: "Nice products",
    },
  ],
};

export default data;
