import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "john123@Gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Chirstopher",
      email: "chris@Gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "Nike slim shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality products",
    },
    {
      name: "Addidas slim shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 130,
      countInStock: 12,
      brand: "Addidas",
      rating: 3,
      numReviews: 8,
      description: "Great T shirt",
    },
    {
      name: "Puma slim shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 100,
      countInStock: 50,
      brand: "Puma",
      rating: 5,
      numReviews: 5,
      description: "Great products",
    },
    {
      name: "Nike Trousers",
      category: "pants",
      image: "/images/p4.jpg",
      price: 80,
      countInStock: 0,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality products",
    },
    {
      name: "Puma Trousers",
      category: "pants",
      image: "/images/p5.jpg",
      price: 150,
      countInStock: 15,
      brand: "Puma",
      rating: 5,
      numReviews: 6,
      description: "High quality products",
    },
    {
      name: "Ducati Trousers",
      category: "pants",
      image: "/images/p6.jpg",
      price: 200,
      countInStock: 11,
      brand: "Ducati",
      rating: 3,
      numReviews: 7,
      description: "Nice products",
    },
    {
      name: "Xbox One(1TB)",
      category: "electronics",
      image: "/images/xbox.jpg",
      price:  900,
      countInStock: 11,
      brand: "Microsoft",
      rating: 5,
      numReviews: 30,
      description: "The 1TB limited edition console encapsulates the urban decay and vibrant Tech of night city with glowing elements, bright panels, color shift effects, and textures",
    },
    {
      name: "Samsung TV",
      category: "electronics",
      image: "/images/samsungtv.jpg",
      price:  1200,
      countInStock: 20,
      brand: "Samsung",
      rating: 4,
      numReviews: 25,
      description: "Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz. Connectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 1 USB ports to connect hard drives and other USB devices. Display : LED Panel | Mega Contrast | PurColor | HD Picture Quality | Slim & Stylish Design",
    },
  ],
};

export default data;
