const data = {
    products: [
        {
            _id: '1',
            name: 'nike slim shirt',
            category: 'shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality products',
        },
        {
            _id: '2',
            name: 'Addidas slim shirt',
            category: 'shirts',
            image: '/images/p2.jpg',
            price: 130,
            brand: 'Addidas',
            rating: 4,
            numReviews: 8,
            description: 'Great T shirt',
        },
        {
            _id: '3',
            name: 'Puma slim shirt',
            category: 'shirts',
            image: '/images/p3.jpg',
            price: 100,
            brand: 'Puma',
            rating: 5,
            numReviews: 5,
            description: 'Great products',
        },
        {
            _id: '4',
            name: 'nike Trousers',
            category: 'pants',
            image: '/images/p4.jpg',
            price: 80,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality products',
        },
        {
            _id: '5',
            name: 'Puma Trousers',
            category: 'pants',
            image: '/images/p5.jpg',
            price: 150,
            brand: 'Puma',
            rating: 5,
            numReviews: 6,
            description: 'High quality products',
        },
        {
            _id: '6',
            name: 'Ducati Trousers',
            category: 'pants',
            image: '/images/p6.jpg',
            price: 200,
            brand: 'Ducati',
            rating: 4.5,
            numReviews: 7,
            description: 'Nice products',
        },
    ]
};

export default data;